- hosts: all
  connection: local
  become: yes
  become_method: sudo
  tasks:
    - name: enable EPEL yum repository
      command: yum-config-manager --enable epel

    - name: copy MongoDB yum repository config
      copy: src=mongodb.repo dest=/etc/yum.repos.d/mongodb.repo owner=root group=root mode=0644

    - name: install requisite RPMs
      yum: name="{{ item }}" state=present
      with_items:
        - git
        - python-pip
        - python-virtualenv
        - mongodb-org
        - mongodb-org-server

    - name: install pips
      pip: name=eve state=present

    - name: start and enable mongodb service
      service: name=mongod state=running enabled=yes

    - name: clone cmdb project from git
      git: repo=https://github.com/PeteTheAutomator/cmdb.git dest=/usr/local/cmdb
