#!/usr/bin/env python

import ConfigParser
import argparse
import json
from cmdb_libs.audit import YumHandler, FacterHandler, HostMetadata, RepoHandler


config = ConfigParser.ConfigParser()
config.read('/etc/cmdb/server.conf')


def argparser():
    parser = argparse.ArgumentParser()
    parser.add_argument('-o', '--output', choices=['stdout', 'server'], default='stdout',
                        help='where to output the results')
    parsed_args = parser.parse_args()
    return vars(parsed_args)


if __name__ == '__main__':
    # TODO: unify the config
    config_dict = dict()
    config_dict['repo_url'] = config.get('defaults', 'repo_url')
    rh = RepoHandler(config=config_dict)

    args = argparser()
    #instance_id = HostMetadata().get()
    instance_id = 'i-defghi12'
    rpm_packages = YumHandler().get()
    facts = FacterHandler().get()

    results = {
        'instance_id': instance_id,
        'rpm_packages': rpm_packages,
        'facts': facts,
    }

    if args['output'] == 'stdout':
        print json.dumps(results, indent=4)
    elif args['output'] == 'server':
        rh.post_audit(instance_id, results)
